
## fabric sdk配置文件路径
fabric:
  sdk:
    config:
      path: D:\\workspace\\go\\src\\github.com\\lifegoeson\\blockchain-benchmark\\config\\config_e2e.yaml

network:
  channel:
    name: mychannel
  endorser_peers:
    peer0_org1: peer0_org1
    peer0_org2: peer0_org2
  chaincode:
    invoke_function:

invoke:
  goroutine:
    count: 20
    test_case_count: 2
query:
  goroutine:
    count: 20
    test_case_count: 5
